version: '3.8'

services:
  app:
    image: laravelsail/php83-composer:latest
    container_name: hudson-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /app/database/database.sqlite
    command: >
      bash -c "
        composer install &&
        php artisan key:generate &&
        php artisan config:clear &&
        php artisan cache:clear &&
        php artisan view:clear &&
        php artisan route:clear &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
